name: My First Workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Ensure code is checked out

      - name: Welcome message
        run: echo "My first Github Actions Job"

      - name: List files
        run: ls -la  # Verify existence of README.md

      - name: Read file
        run: cat README.md  # Assuming it's in the root directory
